name: assembly
channels:
  - auto
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - argparse=1.2.1=py27_0
  - ca-certificates=2020.7.22=0
  - catkin_pkg=0.1.26=py27_0
  - certifi=2019.11.28=py27_0
  - docutils=0.15.2=py27_0
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - python=2.7.18=h15b4118_1
  - python-dateutil=2.2=py27_0
  - readline=8.0=h7b6447c_0
  - setuptools=44.0.0=py27_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.35.1=py_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - open3d-ros-helper==0.0.1.6
    - pip==20.2.3
    - pyside2==5.15.1
    - ros-numpy==0.0.3
    - shiboken2==5.15.1
    - torch==1.3.0
    - torchvision==0.4.1
prefix: /home/demo/anaconda3/envs/assembly
